### ISSUE TITLE
Departure times incorrect

### ISSUE THREAD

**Issue by orlopau** [nadeldrucker/TrafficSwipe#33]
Departure times are incorrect.

**Comment by Philipp97714** [comment]
Current behavior: (Queries from the same time)

![image](https://user-images.githubusercontent.com/12154508/70379234-75915100-192a-11ea-86d5-770392654b85.png)

![image](https://user-images.githubusercontent.com/12154508/70379265-f51f2000-192a-11ea-93c2-348aa18991be.png)

**Comment by Philipp97714** [comment]
@orlopau If I subtract the delay from the departure (because you said you added it) I get the following result. You can check it on branch TS-033/departure-offset/temp

![image](https://user-images.githubusercontent.com/12154508/70379361-e2f1b180-192b-11ea-9b1a-a794bf8aca3a.png)

![image](https://user-images.githubusercontent.com/12154508/70379381-22b89900-192c-11ea-8766-01b329637ed0.png)

**Comment by orlopau** [comment]
Fixed
